### ISSUE TITLE
$strClass returns empty in DataContainer.php ln #278

### ISSUE THREAD

**Issue by vrisiniinfotech** [m-vo/contao-group-widget#24]
Hi,

I just installed your package through the Contao Manager and all shows good. I simply copied your code snippet for one of my DCA fields, reset the cache, dumped the autoloader and reloaded the form. Unfortunately, the field disappeared without leaving any errors in the log. So, I looked for the problem in DataContainer.php and narrowed it down to the fact that the class is not found in line 278. Further var_dump revealed there to be no entry for "group" in $GLOBALS['BE_FFL'] array.

Contao version is 4.9.16 and Contao Manager is 1.4.4
Can you please tell me what I might be missing here?

Thanks a lot in advance.

Best regards,
Anupam
![Screen Shot 2021-07-06 at 10 51 11 PM](https://user-images.githubusercontent.com/80465697/124641801-b8236280-deac-11eb-83d5-1f14248f912e.png)

**Comment by m-vo** [comment]
> Further var_dump revealed there to be no entry for "group" in $GLOBALS['BE_FFL'] array.

This is expected. There is no actual widget, the group wrappers and fields are generated on the fly.

Most likely your DCA isn't correct. Can you post the full file?

**Comment by vrisiniinfotech** [comment]
Hey,

Thanks a lot for your prompt response, I really appreciate that.
Please find the DCA file enclosed for your reference as a text file because ".php" file extension is not allowed. The field is "course_curriculum" and you can find it in line 105.

Looking forward to your response.

Best regards,
Anupam

[vi_courses_main.txt](https://github.com/m-vo/contao-group-widget/files/6772282/vi_courses_main.txt)

**Comment by m-vo** [comment]
There are multiple errors in your file:

- Remove the spaces from your palette definition, otherwise the field names cannot be parsed correctly. This is something that we should probably harden in the extension (see #25). You'll then see the actual errors within your group definition.
- Such as: The field `singleSRC` and `text` do not exist. You must either define them as normal DCA fields or as inline group fields.

Besides this your DCA won't work because it's missing an `id` and `tstamp` field. Also you should probably prefix the name with `tl_` because otherwise the database migrations in 4.9 won't kick in.

You might want to check out this guide on how to create DCAs: https://docs.contao.org/dev/guides/dca/

Closing as it has nothing to do with the extension. Feel free to report back if there is still something odd and you think it has to do with the extension.

**Comment by vrisiniinfotech** [comment]
Thanks a lot Moritz for the valuable feedback and the pointers. 
Guess, I need to read the changelogs and documentation more closely. Regarding the spaces, PHP is freeform and never realized over all these years that they might create an issue until you pointed it out. id and tstamp are default fields and I don't think they need to be explicitly defined in each DCA. Never had an issue with it so far. For the table name, I still miss sometimes the idea with database.sql :-) But, in this case its intentional as I don't want Contao to bother with some of these custom tables.

Now, to a question actually, because I am using your widget to build an extremely complicated form!
Is it possible to have the group field within another group field? I tried that and it didn't work. Maybe, I was stupid enough to make another mistake, can you just take a look into the code block given below?
------
'course_curriculum' => array
(
	'label'                 => &$GLOBALS['TL_LANG']['vi_courses_main']['course_curriculum'],
	'exclude'               => true,
	'search'                => true,
	'inputType' 			=> 'group',
	'palette' 				=> ['title','lektionen'],   
	'fields'			 	=> [
									'title' => [ // additional field, defined inline
										'label'	=> ['Title', 'Please enter the title', ''],
										'inputType' => 'text'
									],											
									'lektionen' => [
										'label'	=> ['Beschreibe diesen Abschnitt', ''],
										'inputType' => 'group',
										'palette'	=> ['lek_title'],
										'fields'	=> [
											'lek_title'	=> [
												'label'	=> ['Neu erstellen lektion', ''],
												'inputType' => 'text',
											],
										],
										'min'	=> 1,
										'max'	=> 5,
										'order'	=> false,
									],
								],   
	
	// force at least 1, at max 5 elements
	'min' 					=> 1,
	'max' 					=> 5,
	
	// disable ordering (on by default)
	'order' 				=> false,
	
	// store serialized into a blob (default storage backend)
	'sql' 					=> [
								'type' => 'blob',
								'length' => \Doctrine\DBAL\Platforms\MySqlPlatform::LENGTH_LIMIT_BLOB,
								'notnull' => false,
							],
),
------

Regards,
Anupam

**Comment by m-vo** [comment]
> Is it possible to have the group field within another group field?

No, you cannot nest groups.

**Comment by vrisiniinfotech** [comment]
Thanks a lot Moritz, you have already done a great job with this module and I am really thankful to you. It's only obvious that other people also need to do something. So, I already figured that nesting was not possible and implemented a custom widget of my own as the fields within. Now, the entire thing works like charm and exactly the way required.

Once again, I thank you for the great contribution and hope that you keep up with it. As a mark of respect, I attach a small screenshot of the final work for your visual delight, it really looks great :-)
![Screen Shot 2021-07-08 at 1 46 11 PM](https://user-images.githubusercontent.com/80465697/124888075-66392480-dff3-11eb-865a-08f4afb615b0.png)
