### ISSUE TITLE
Widget gets not properly loaded when in subpalette

### ISSUE THREAD

**Issue by bytehead** [m-vo/contao-group-widget#26]
After the `submitOnChange` event (when clicking the checkbox to display the subpalette): 

![Bildschirmfoto 2021-07-07 um 12 52 15](https://user-images.githubusercontent.com/754921/124747483-4259de00-df22-11eb-9f7e-19e159a5b615.png)

after save or refresh:

![Bildschirmfoto 2021-07-07 um 12 52 22](https://user-images.githubusercontent.com/754921/124747581-5bfb2580-df22-11eb-9f75-8f2677918176.png)

**Comment by m-vo** [comment]
see #27
