### ISSUE TITLE
Neues Feld legt sich an, obwohl vorher Pflichtfelder missachtet wurden

### ISSUE THREAD

**Issue by k-webdesign** [m-vo/contao-group-widget#32]
Hey Moritz,

wenn ich ein Feld anlege und es ein leeres Pflichtfeld hat, z.B. Text, dann erscheint das neue Feld. Ist soweit nicht schlimm, doch wenn man dann im fälschlicherweise neu angelegten Feld etwas ändern möchte (Bild uploaden z.B.), dann passiert da nichts. Weil es eigentlich nicht da ist. Bei einem Reload ist das Feld dann wieder weg. 

Das ist ziemlich irreführend, wenn man die Felder anlegt und dann denkt, man könne jetzt alle auf einmal abarbeiten und am Ende speichern. Besser wäre es, wenn sich das neue Feld nicht anlegt und stattdessen die Fehlermeldung erscheint, dass XXX ein Pflichtfeld ist.

**Comment by m-vo** [comment]
Ich glaube ich hab noch nicht ganz verstanden, was das Problem ist. Kannst du einen Reproducer deiner DCA Konfiguration erstellen bei der das Problem auftritt und hier posten?

**Comment by m-vo** [comment]
This issue will be fixed with #48.
