### ISSUE TITLE
Versionizing not working?

### ISSUE THREAD

**Issue by aschempp** [m-vo/contao-group-widget#39]
Could it be possible that version control does not work with the group widget? 

Since the widget stores the data on its own, the `DataContainer` will not create a new version if only a group widget was changes. The `tl_version` table will also not contain these changes (if serialized storage is used).

If using the serialized storage, the most simple solution is probably to set `$dc->createNewVersion = true` if there are changes. Dunno if the widget knows/can handle that.

For entity storage it is gonna be much more complex, since you would need to register `onversion` and `onrestore` callbacks to dynamically and and revert the external table changes. I did something similar in Isotope for product categories in a subtable if you need an idea: https://github.com/isotope/core/blob/2.7/system/modules/isotope/library/Isotope/Backend/Product/Category.php#L51-L125

**Comment by m-vo** [comment]
Closing in favor of #41, #40
