### ISSUE TITLE
exclude entfernt Feld in Ausgabe

### ISSUE THREAD

**Issue by christianbarkowsky** [m-vo/contao-group-widget#43]
Wenn im Widget ein Feld die Reference **exclude** besitzt, wird das Feld in der Ausgabe entfernt

Siehe DC_Table >> https://github.com/contao/contao/blob/01d8f3ea25115aaf01297c9662ed59f7142a858e/core-bundle/src/Resources/contao/drivers/DC_Table.php#L1829

**Comment by m-vo** [comment]
This issue should also have resolved itself with 234edff0ef58bcf6592dd6e99deca8c991de9931. :slightly_smiling_face:
