### ISSUE TITLE
Lacking compatibility with Conto 5.0.1 i.e. Symphony 6

### ISSUE THREAD

**Issue by Seefahrer** [m-vo/contao-group-widget#45]
The installation of that extension as dependency of "fritzmg/contao-swiper" throws fllwg self-explaining error message in CM:

`The service "Mvo\ContaoGroupWidget\Group\Registry" has a dependency on a non-existent service "Psr\Container\ContainerInterface".`

The specified service-alias had been removed in Symphony 6.

**Comment by m-vo** [comment]
See #47
