### ISSUE TITLE
C5: Error on installation

### ISSUE THREAD

**Issue by kikmedia** [m-vo/contao-group-widget#49]
Whilst trying to install https://github.com/inspiredminds/contao-fieldset-duplication, I've got the following error message from Contao Manager, referencing to your widget:
```
In CheckExceptionOnInvalidReferenceBehaviorPass.php line 86:
  The service "Mvo\ContaoGroupWidget\Group\Registry" has a dependency on a non-existent service "Psr\Container\ContainerInterface". 
```
Not shure how to circumvent this.

**Comment by m-vo** [comment]
Which version of the group widget gets installed? This issue should already be fixed in version 1.4.1.

You can find out by running `composer show | grep mvo/contao-group-widget`.

**Comment by heimseiten** [comment]
I get the same error, even if I install only mvo/contao-group-widget (1.4.1) on Contao 5. Thank you!

**Comment by kikmedia** [comment]
I tried to install the mentioned version 1.4.1 on Contao 5.04, PHP 8.1.11

**Comment by m-vo** [comment]
Ah, now I know why I'm seeing a different result - the changes did not make it in the release, yet. :see_no_evil: Sorry for the inconvenience.

I'll tag a new version as soon as #48 is merged, which should be upcoming shortly.
