### ISSUE TITLE
Incompatibility with Contao 5.3

### ISSUE THREAD

**Issue by aschempp** [m-vo/contao-group-widget#55]
Contao 5.3 requires `doctrine/collections: ^2.1` but this package requires `doctrine/collections: ^1.4`. Not sure if we can easily update the dependency?

**Comment by m-vo** [comment]
We can probably just allow `^1.4 || ^2.1`. 

Judging by the [2.0 upgrade docs](https://github.com/doctrine/collections/blob/2.1.x/UPGRADE.md#upgrade-to-20) only type hints were added, so this should only affect sub classes of their classes (which we don't have).

**Comment by aschempp** [comment]
Would you do that quick fix or need a pull request? 🙃

**Comment by m-vo** [comment]
Fixed in #56 and released as v1.5.5.
