### ISSUE TITLE
Create a new element under Contao 5.4 not possible

### ISSUE THREAD

**Issue by hendrikbengs** [m-vo/contao-group-widget#62]
After upgrading to Contao 5.4 (PHP 8.3) it is no longer possible to create new elements within the group element. The button becomes the state `disabled`.

**Comment by richardhj** [comment]
<img width="886" alt="Screenshot 2024-09-06 at 20 36 07" src="https://github.com/user-attachments/assets/ed1f3650-d11d-412c-a567-3fb4042742ed">
<img width="996" alt="Screenshot 2024-09-06 at 20 35 57" src="https://github.com/user-attachments/assets/3943d2d7-5d26-4053-86ec-27f72f4451f5">

**Comment by richardhj** [comment]
This change is the culpirt, becasuse `.wiget-group` now can have no `widget-group--container` elements.

https://github.com/contao/contao/commit/c8e1d2553a41ffc8e228107cb9a35c69a5200eac#diff-fb74744bd45d8f0f5c3207987a6ae2d1456f2dc7f06467cb14c133bafe18b927R188
