### ISSUE TITLE
Error when not implementing position in entity storage

### ISSUE THREAD

**Issue by heimrich-hannot** [m-vo/contao-group-widget#65]
I implemented an entity storage with group widget. I do not need the position, so I skipped implementing it.

I get following error: 
![image](https://github.com/user-attachments/assets/2f165141-e6e5-4d1f-9707-c8c70f89f7e3)

My entity extends `AbstractGroupElementEntity`, where the comment above `position` stating `Defining this field is optional`.
But the `ObjectAccessor` return true for support and `EntityStorage::getElementPosition()` return null, since the value is null in my entity (seems to be filled with null by doctrine). Maybe there should be an additional check for the db field?

**Comment by m-vo** [comment]
Did you define `'order' => false` in your group definition?

**Comment by m-vo** [comment]
Maybe either `getElements()` must not call `getElementPosition()` in that case or `getElementPosition()` should just allow `null` as a return value. :thinking: 

Could you check if the latter would solve the issue?

**Comment by koertho** [comment]
> Did you define `'order' => false` in your group definition?
Yes


> Maybe either `getElements()` must not call `getElementPosition()` in that case or `getElementPosition()` should just allow `null` as a return value. 🤔
> 
> Could you check if the latter would solve the issue?

Seems to work.

**Comment by m-vo** [comment]
See #66
