### ISSUE TITLE
Records are getting deleted - Contao 5.4.8

### ISSUE THREAD

**Issue by xApep** [m-vo/contao-group-widget#67]
I have notice two things.

First one is that there is a bug, where second record (I did not tested with more then 2) is deleted if you edit the first records.

Second is that each time you save the DCA, button (PLUS) is disabled and then you need to refresh a page, to add new records.

I have records the video.

Contao 5.4.8
contao-group-widget v1.5.9

https://github.com/user-attachments/assets/184cc9f0-6348-4f46-853f-004c3316e942

**Comment by ausi** [comment]
Can you share the DCA config you used?

**Comment by xApep** [comment]
`'test2' => [
	'inputType' => 'group',
	'palette' => ['amount', 'currency'],
	'fields' => [
		'amount' => [ // additional field, defined inline
			'inputType' => 'text',
			'eval' => ['tl_class' => 'w50'],
		],
		'currency' => [ // let's change some properties of the existing field
			'inputType' => 'text',
			'eval' => ['tl_class' => 'w50'],
		]
	],

	// force at least 1, at max 5 elements
	'min' => 1,
	'max' => 5,

	// disable ordering (on by default)
	'order' => false,

	// store serialized into a blob (default storage backend)
	'sql' => [
		'type' => 'blob',
		'length' => \Doctrine\DBAL\Platforms\MySQLPlatform::LENGTH_LIMIT_BLOB,
		'notnull' => false,
	],
]`

**Comment by m-vo** [comment]
Thanks for the report. Fixed in #68 and released as [v1.5.10.](https://github.com/m-vo/contao-group-widget/releases/tag/v1.5.10)
